### ISSUE TITLE
Register confirmation error

### ISSUE THREAD

**Issue by hotrush** [chelvmeste/vmeste#1]
Wrong site link in confirmation email

**Comment by chelvmeste** [comment]
Опять не приходит письмо мне на nikolay.olkhovsky@gmail.com
Первый раз попытался ввести мыло и пароль, просто письмо не пришло. Второй раз вылезло вот это удовольствие.
![image](https://cloud.githubusercontent.com/assets/8860649/6691940/7d009256-cceb-11e4-9c96-124bf0a89fa8.png)

**Comment by hotrush** [comment]
да, про письма забыл сказать. не пустило в админку мандрила, ты не менял
пароль?

17 марта 2015 г., 19:20 пользователь chelvmeste notifications@github.com
написал:

**Comment by chelvmeste** [comment]
Нет. Мандрил не трогал.

**Comment by chelvmeste** [comment]
Восстановил пароль. Пароль старый.
