### ISSUE TITLE
Исправить

### ISSUE THREAD

**Issue by chelvmeste** [chelvmeste/vmeste#25]
после того, как один раз обратился к человеку и успешно заполнил форму обратной связи, зеленая кнопка “Обратиться” не возвращается.

**Comment by hotrush** [comment]
Я уже фиксил, проверьте еще раз
![vmeste1](https://cloud.githubusercontent.com/assets/1247004/7252877/243570c6-e841-11e4-87e3-c3190e155435.gif)
