### ISSUE TITLE
Поле комментарии

### ISSUE THREAD

**Issue by chelvmeste** [chelvmeste/vmeste#26]
Система не дает закрыть заявку или исполненное дело,или отменить заявку не заполнив поле с комментариями.

**Comment by hotrush** [comment]
Ну да, так было в тз написано) В чем ошибка?

**Comment by chelvmeste** [comment]
Есть ощущение, что это излишнее насилие по отношению к пользователям. Пока не исправляй - еще пособираем обратную связь.
