### ISSUE TITLE
Русский язык

### ISSUE THREAD

**Issue by chelvmeste** [chelvmeste/vmeste#27]
Все комментарии к ошибкам, которые появляются в ходе неправильных действий, на английском языке, к сожалению не все его знают :D

**Comment by hotrush** [comment]
Подробней пожалуйста, мне казалось я уже все ошибки перевел
![_115](https://cloud.githubusercontent.com/assets/1247004/7252675/d8297bec-e83f-11e4-9716-263e132da9d3.png)

**Comment by chelvmeste** [comment]
Ошибка с локалхостом вылазила на английском. Сейчас, вроде, ОК.
