### ISSUE TITLE
Подтверждение регистрации

### ISSUE THREAD

**Issue by chelvmeste** [chelvmeste/vmeste#37]
Из-за проблемы с фреймворком мы не можем делать рассылку через Email. А рассылка нам очень нужна! Нужно либо надежно решить проблему с Email, либо прикрутить к сайту СМС-рассылку (СМС - предпочтительнее). Мы сейчас работаем с www.sms24x7.ru

**Comment by hotrush** [comment]
выключил очередь для писем, все шлется в рантайме. проблем больше не будет
