### ISSUE TITLE
Проблема с позиционированием карты

### ISSUE THREAD

**Issue by chelvmeste** [chelvmeste/vmeste#6]
Если кто-то вдруг взял и ввел адрес в Африке, карта сразу пытается отобразить все адреса, и в итоге показывает не Челябинск, а половину планеты. Задумка, подстраивать масштаб под размещенные на карте метки - хорошая, но все же прошу просто настроить карту, что она в стартовой позиции отображала Челябинск (целиком) и все метки на нем.
Также прошу в комментариях указать в каком файле и строчках кода задается эта настройка, чтобы каждый раз не дергать, если вдруг захочется подправить масштаб или центр карты.

**Comment by hotrush** [comment]
править в файле app/config/geo.php
