### ISSUE TITLE
Ошибка соединения с локалхостом

### ISSUE THREAD

**Issue by chelvmeste** [chelvmeste/vmeste#9]
![1 2 1](https://cloud.githubusercontent.com/assets/8860649/6605890/4c4c239a-c855-11e4-827e-a557b2e899b0.jpg)

При этом карточка добровольца успешно добавилась, но не сохранился адрес.
http://dev.projectvmeste.ru/help-offer/20

**Comment by hotrush** [comment]
этой ошибки не наблюдаю. localhost:9200 это elasticsearch. учитывая последние события он мог просто лежать/быть недоступен. закрываю пока не повторится
